# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import article_pb2 as protos_dot_article__pb2


class ArticleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateArticle = channel.unary_unary(
                '/article.ArticleService/CreateArticle',
                request_serializer=protos_dot_article__pb2.CreateArticleRequest.SerializeToString,
                response_deserializer=protos_dot_article__pb2.CreateArticleResponse.FromString,
                )
        self.FindAllArticle = channel.unary_unary(
                '/article.ArticleService/FindAllArticle',
                request_serializer=protos_dot_article__pb2.FindAllArticleRequest.SerializeToString,
                response_deserializer=protos_dot_article__pb2.FindAllArticleResponse.FromString,
                )
        self.FindOneArticle = channel.unary_unary(
                '/article.ArticleService/FindOneArticle',
                request_serializer=protos_dot_article__pb2.FindOneArticleRequest.SerializeToString,
                response_deserializer=protos_dot_article__pb2.FindOneArticleResponse.FromString,
                )
        self.FindArticleByName = channel.unary_unary(
                '/article.ArticleService/FindArticleByName',
                request_serializer=protos_dot_article__pb2.FindArticleByNameRequest.SerializeToString,
                response_deserializer=protos_dot_article__pb2.FindArticleByNameResponse.FromString,
                )
        self.UpdateArticle = channel.unary_unary(
                '/article.ArticleService/UpdateArticle',
                request_serializer=protos_dot_article__pb2.UpdateArticleRequest.SerializeToString,
                response_deserializer=protos_dot_article__pb2.UpdateArticleResponse.FromString,
                )
        self.DeleteArticle = channel.unary_unary(
                '/article.ArticleService/DeleteArticle',
                request_serializer=protos_dot_article__pb2.DeleteArticleRequest.SerializeToString,
                response_deserializer=protos_dot_article__pb2.DeleteArticleResponse.FromString,
                )
        self.CreateSummary = channel.unary_unary(
                '/article.ArticleService/CreateSummary',
                request_serializer=protos_dot_article__pb2.CreateSummaryRequest.SerializeToString,
                response_deserializer=protos_dot_article__pb2.CreateSummaryResponse.FromString,
                )
        self.FindAllSummary = channel.unary_unary(
                '/article.ArticleService/FindAllSummary',
                request_serializer=protos_dot_article__pb2.FindAllSummaryRequest.SerializeToString,
                response_deserializer=protos_dot_article__pb2.FindAllSummaryResponse.FromString,
                )
        self.FindOneSummary = channel.unary_unary(
                '/article.ArticleService/FindOneSummary',
                request_serializer=protos_dot_article__pb2.FindOneSummaryRequest.SerializeToString,
                response_deserializer=protos_dot_article__pb2.FindOneSummaryResponse.FromString,
                )
        self.UpdateSummary = channel.unary_unary(
                '/article.ArticleService/UpdateSummary',
                request_serializer=protos_dot_article__pb2.UpdateSummaryRequest.SerializeToString,
                response_deserializer=protos_dot_article__pb2.UpdateSummaryResponse.FromString,
                )
        self.DeleteSummary = channel.unary_unary(
                '/article.ArticleService/DeleteSummary',
                request_serializer=protos_dot_article__pb2.DeleteSummaryRequest.SerializeToString,
                response_deserializer=protos_dot_article__pb2.DeleteSummaryResponse.FromString,
                )


class ArticleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindAllArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindOneArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindArticleByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindAllSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindOneSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArticleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateArticle,
                    request_deserializer=protos_dot_article__pb2.CreateArticleRequest.FromString,
                    response_serializer=protos_dot_article__pb2.CreateArticleResponse.SerializeToString,
            ),
            'FindAllArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.FindAllArticle,
                    request_deserializer=protos_dot_article__pb2.FindAllArticleRequest.FromString,
                    response_serializer=protos_dot_article__pb2.FindAllArticleResponse.SerializeToString,
            ),
            'FindOneArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.FindOneArticle,
                    request_deserializer=protos_dot_article__pb2.FindOneArticleRequest.FromString,
                    response_serializer=protos_dot_article__pb2.FindOneArticleResponse.SerializeToString,
            ),
            'FindArticleByName': grpc.unary_unary_rpc_method_handler(
                    servicer.FindArticleByName,
                    request_deserializer=protos_dot_article__pb2.FindArticleByNameRequest.FromString,
                    response_serializer=protos_dot_article__pb2.FindArticleByNameResponse.SerializeToString,
            ),
            'UpdateArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateArticle,
                    request_deserializer=protos_dot_article__pb2.UpdateArticleRequest.FromString,
                    response_serializer=protos_dot_article__pb2.UpdateArticleResponse.SerializeToString,
            ),
            'DeleteArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteArticle,
                    request_deserializer=protos_dot_article__pb2.DeleteArticleRequest.FromString,
                    response_serializer=protos_dot_article__pb2.DeleteArticleResponse.SerializeToString,
            ),
            'CreateSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSummary,
                    request_deserializer=protos_dot_article__pb2.CreateSummaryRequest.FromString,
                    response_serializer=protos_dot_article__pb2.CreateSummaryResponse.SerializeToString,
            ),
            'FindAllSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.FindAllSummary,
                    request_deserializer=protos_dot_article__pb2.FindAllSummaryRequest.FromString,
                    response_serializer=protos_dot_article__pb2.FindAllSummaryResponse.SerializeToString,
            ),
            'FindOneSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.FindOneSummary,
                    request_deserializer=protos_dot_article__pb2.FindOneSummaryRequest.FromString,
                    response_serializer=protos_dot_article__pb2.FindOneSummaryResponse.SerializeToString,
            ),
            'UpdateSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSummary,
                    request_deserializer=protos_dot_article__pb2.UpdateSummaryRequest.FromString,
                    response_serializer=protos_dot_article__pb2.UpdateSummaryResponse.SerializeToString,
            ),
            'DeleteSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSummary,
                    request_deserializer=protos_dot_article__pb2.DeleteSummaryRequest.FromString,
                    response_serializer=protos_dot_article__pb2.DeleteSummaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'article.ArticleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ArticleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/article.ArticleService/CreateArticle',
            protos_dot_article__pb2.CreateArticleRequest.SerializeToString,
            protos_dot_article__pb2.CreateArticleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindAllArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/article.ArticleService/FindAllArticle',
            protos_dot_article__pb2.FindAllArticleRequest.SerializeToString,
            protos_dot_article__pb2.FindAllArticleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindOneArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/article.ArticleService/FindOneArticle',
            protos_dot_article__pb2.FindOneArticleRequest.SerializeToString,
            protos_dot_article__pb2.FindOneArticleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindArticleByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/article.ArticleService/FindArticleByName',
            protos_dot_article__pb2.FindArticleByNameRequest.SerializeToString,
            protos_dot_article__pb2.FindArticleByNameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/article.ArticleService/UpdateArticle',
            protos_dot_article__pb2.UpdateArticleRequest.SerializeToString,
            protos_dot_article__pb2.UpdateArticleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/article.ArticleService/DeleteArticle',
            protos_dot_article__pb2.DeleteArticleRequest.SerializeToString,
            protos_dot_article__pb2.DeleteArticleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/article.ArticleService/CreateSummary',
            protos_dot_article__pb2.CreateSummaryRequest.SerializeToString,
            protos_dot_article__pb2.CreateSummaryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindAllSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/article.ArticleService/FindAllSummary',
            protos_dot_article__pb2.FindAllSummaryRequest.SerializeToString,
            protos_dot_article__pb2.FindAllSummaryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindOneSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/article.ArticleService/FindOneSummary',
            protos_dot_article__pb2.FindOneSummaryRequest.SerializeToString,
            protos_dot_article__pb2.FindOneSummaryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/article.ArticleService/UpdateSummary',
            protos_dot_article__pb2.UpdateSummaryRequest.SerializeToString,
            protos_dot_article__pb2.UpdateSummaryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/article.ArticleService/DeleteSummary',
            protos_dot_article__pb2.DeleteSummaryRequest.SerializeToString,
            protos_dot_article__pb2.DeleteSummaryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
