# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/file.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/file.proto\x12\x04\x66ile\":\n\x08\x46ileInfo\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x66ileName\x18\x02 \x01(\t\x12\x10\n\x08\x66ileType\x18\x03 \x01(\t\"C\n\x11UploadFileRequest\x12\x1c\n\x04info\x18\x01 \x01(\x0b\x32\x0e.file.FileInfo\x12\x10\n\x08\x66ileData\x18\x02 \x01(\x0c\"3\n\x12UploadFileResponse\x12\x0e\n\x06status\x18\x01 \x01(\x03\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"3\n\x13\x44ownloadFileRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x66ileName\x18\x02 \x01(\t\"(\n\x14\x44ownloadFileResponse\x12\x10\n\x08\x66ileData\x18\x01 \x01(\x0c\"6\n\x16\x44ownloadFileTXTRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x66ileName\x18\x02 \x01(\t\"+\n\x17\x44ownloadFileTXTResponse\x12\x10\n\x08\x66ileData\x18\x01 \x01(\x0c\x32\xf1\x01\n\x0b\x46ileService\x12\x43\n\nUploadFile\x12\x17.file.UploadFileRequest\x1a\x18.file.UploadFileResponse\"\x00(\x01\x12I\n\x0c\x44ownloadFile\x12\x19.file.DownloadFileRequest\x1a\x1a.file.DownloadFileResponse\"\x00\x30\x01\x12R\n\x0f\x44ownloadFileTXT\x12\x1c.file.DownloadFileTXTRequest\x1a\x1d.file.DownloadFileTXTResponse\"\x00\x30\x01\x42\nZ\x08./pkg/pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.file_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010./pkg/pb'
  _FILEINFO._serialized_start=27
  _FILEINFO._serialized_end=85
  _UPLOADFILEREQUEST._serialized_start=87
  _UPLOADFILEREQUEST._serialized_end=154
  _UPLOADFILERESPONSE._serialized_start=156
  _UPLOADFILERESPONSE._serialized_end=207
  _DOWNLOADFILEREQUEST._serialized_start=209
  _DOWNLOADFILEREQUEST._serialized_end=260
  _DOWNLOADFILERESPONSE._serialized_start=262
  _DOWNLOADFILERESPONSE._serialized_end=302
  _DOWNLOADFILETXTREQUEST._serialized_start=304
  _DOWNLOADFILETXTREQUEST._serialized_end=358
  _DOWNLOADFILETXTRESPONSE._serialized_start=360
  _DOWNLOADFILETXTRESPONSE._serialized_end=403
  _FILESERVICE._serialized_start=406
  _FILESERVICE._serialized_end=647
# @@protoc_insertion_point(module_scope)
