# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import summary_pb2 as protos_dot_summary__pb2


class SummaryTextServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SummaryTextRank = channel.unary_unary(
                '/summary.SummaryTextService/SummaryTextRank',
                request_serializer=protos_dot_summary__pb2.SummaryTextRequest.SerializeToString,
                response_deserializer=protos_dot_summary__pb2.SummaryTextResponse.FromString,
                )
        self.SummaryLSA = channel.unary_unary(
                '/summary.SummaryTextService/SummaryLSA',
                request_serializer=protos_dot_summary__pb2.SummaryLSARequest.SerializeToString,
                response_deserializer=protos_dot_summary__pb2.SummaryLSAResponse.FromString,
                )
        self.SummaryT5 = channel.unary_unary(
                '/summary.SummaryTextService/SummaryT5',
                request_serializer=protos_dot_summary__pb2.SummaryT5Request.SerializeToString,
                response_deserializer=protos_dot_summary__pb2.SummaryT5Response.FromString,
                )


class SummaryTextServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SummaryTextRank(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SummaryLSA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SummaryT5(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SummaryTextServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SummaryTextRank': grpc.unary_unary_rpc_method_handler(
                    servicer.SummaryTextRank,
                    request_deserializer=protos_dot_summary__pb2.SummaryTextRequest.FromString,
                    response_serializer=protos_dot_summary__pb2.SummaryTextResponse.SerializeToString,
            ),
            'SummaryLSA': grpc.unary_unary_rpc_method_handler(
                    servicer.SummaryLSA,
                    request_deserializer=protos_dot_summary__pb2.SummaryLSARequest.FromString,
                    response_serializer=protos_dot_summary__pb2.SummaryLSAResponse.SerializeToString,
            ),
            'SummaryT5': grpc.unary_unary_rpc_method_handler(
                    servicer.SummaryT5,
                    request_deserializer=protos_dot_summary__pb2.SummaryT5Request.FromString,
                    response_serializer=protos_dot_summary__pb2.SummaryT5Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'summary.SummaryTextService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SummaryTextService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SummaryTextRank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/summary.SummaryTextService/SummaryTextRank',
            protos_dot_summary__pb2.SummaryTextRequest.SerializeToString,
            protos_dot_summary__pb2.SummaryTextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SummaryLSA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/summary.SummaryTextService/SummaryLSA',
            protos_dot_summary__pb2.SummaryLSARequest.SerializeToString,
            protos_dot_summary__pb2.SummaryLSAResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SummaryT5(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/summary.SummaryTextService/SummaryT5',
            protos_dot_summary__pb2.SummaryT5Request.SerializeToString,
            protos_dot_summary__pb2.SummaryT5Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
